# Replication of study "I will Survive: Predicting Business Failures from Customer Ratings

The following is a replication of the marketing science case study

In [15]:
# Imports
import pandas as pd
import numpy as np
from pathlib import Path

np.random.seed(42)  # random seed for reproducability

data_folder = Path("../data")


# from rich import print

In [16]:
# Dataframes
reviews = pd.read_csv(data_folder / "reviews.csv")
business_covariates = pd.read_csv(data_folder / "business_covariates.csv")

In [17]:
reviews.head(3)

,review_id,business_id,user_id,date,stars,text,funny,cool,useful,Year,first_year,.groups,n_reviews,AggRat,language,tempcontiguity,sentimenttext,wordCount
0,EQF-SyHb_Yg0HC9E9BppOg,--g-a85VwrdZJNf0R95GcQ,SvsoiaCf0WG7UIDJOxJ7Yg,2013-11-14,5,super fresh food..great prices. ala carte and ...,0,1,3,2013,2013,drop,24,5.0,en,0,0.461132,10
1,qfvzHEL0gGxRdTo7NB2fnw,--g-a85VwrdZJNf0R95GcQ,D0YggUjK98hwIpiqXA9y_g,2013-11-18,5,I was in the Kabab House for the first time on...,0,1,3,2013,2013,drop,24,5.0,en,0,0.287281,44
2,_HpIujp_Yvbyk8U6s8nW3Q,--g-a85VwrdZJNf0R95GcQ,8S4b4Adn1laE--nVsu8Udw,2013-12-05,5,"Great food, and great prices. The family and ...",0,1,1,2013,2013,drop,24,5.0,en,0,-0.051979,77

In [18]:
business_covariates.head(3)

,business_id,name,neighborhood,address,city,state,postal_code,latitude,longitude,stars,...,chain,density,TRAIN,category,FT,Price.Level,Restaurant.Size,Number.of.Seats,ZRI,Distance.To.City.Centre
0,QkG3KUXwqZBW18A9k1xqCA,"""Red Lobster""",NaN,"""2810 North 75th Ave""",Phoenix,AZ,85035.0,33.478735,-112.221379,2.5,...,1,11,0,American,False,2.0,700.0,350.0,1248.0,14035.314000
1,5XejqzaFmtkZMstJS5Iy-w,"""D'Lish Cafe""",NaN,"""503 W Thomas Rd""",Phoenix,AZ,85013.0,33.480301,-112.080586,4.0,...,0,17,0,American,False,1.0,200.0,30.0,1557.0,3279.013976
2,M3uV9Y3EDSpy9d4YwyNSAQ,"""Yakiramen""",NaN,"""10605 N 43rd Ave""",Phoenix,AZ,85029.0,33.582363,-112.149884,4.0,...,0,1,0,Asian,False,2.0,280.0,70.0,1291.0,16198.365529

In [19]:
business_covariates.describe()

,neighborhood,postal_code,latitude,longitude,stars,review_count,is_open,Checkin,chain,density,TRAIN,Price.Level,Restaurant.Size,Number.of.Seats,ZRI,Distance.To.City.Centre
count,0.0,920.000000,921.000000,921.000000,921.000000,921.000000,921.000000,921.000000,921.000000,921.000000,921.0,895.000000,786.000000,744.000000,894.000000,921.000000
mean,NaN,85030.322826,33.529524,-112.061840,3.559175,70.539631,0.755700,188.532030,0.287731,12.709012,0.0,1.465922,228.811705,98.099462,1492.515660,13146.992429
std,NaN,34.277926,0.105300,0.065143,0.762594,46.611353,0.429905,200.994147,0.452951,14.809149,0.0,0.516734,259.853114,103.882457,179.943743,8827.957649
min,NaN,85003.000000,33.303193,-112.291920,1.500000,19.000000,0.000000,0.000000,0.000000,1.000000,0.0,1.000000,15.000000,0.000000,1197.000000,89.781019
25%,NaN,85016.000000,33.458871,-112.100589,3.000000,32.000000,1.000000,59.000000,0.000000,4.000000,0.0,1.000000,92.250000,36.000000,1376.000000,6790.519664
50%,NaN,85023.000000,33.508887,-112.065448,3.500000,58.000000,1.000000,120.000000,0.000000,8.000000,0.0,1.000000,156.000000,62.000000,1469.000000,11695.776908
75%,NaN,85037.000000,33.611000,-112.010244,4.000000,95.000000,1.000000,242.000000,1.000000,15.000000,0.0,2.000000,300.000000,120.000000,1558.000000,18825.530336
max,NaN,85339.000000,33.870166,-111.890157,5.000000,200.000000,1.000000,2473.000000,1.000000,86.000000,0.0,3.000000,5400.000000,982.000000,2007.000000,47166.652003

In [20]:
# Display column names and their data types
print("Processed reviews:")
print(reviews.dtypes)
print(f"Length: {len(reviews)}")

Processed reviews:
review_id          object
business_id        object
user_id            object
date               object
stars               int64
text               object
funny               int64
cool                int64
useful              int64
Year                int64
first_year          int64
.groups            object
n_reviews           int64
AggRat            float64
language           object
tempcontiguity      int64
sentimenttext     float64
wordCount           int64
dtype: object
Length: 64887

In [21]:
print("Processed business covariates:")
print(business_covariates.dtypes)
print(f"Length: {len(business_covariates)}")

Processed business covariates:
business_id                 object
name                        object
neighborhood               float64
address                     object
city                        object
state                       object
postal_code                float64
latitude                   float64
longitude                  float64
stars                      float64
review_count                 int64
is_open                      int64
categories                  object
Checkin                      int64
chain                        int64
density                      int64
TRAIN                        int64
category                    object
FT                            bool
Price.Level                float64
Restaurant.Size            float64
Number.of.Seats            float64
ZRI                        float64
Distance.To.City.Centre    float64
dtype: object
Length: 921

In [22]:
# initialize new lists

ratings = []
sentiment = []
days = []
time = []
age = []

business_ids = business_covariates["business_id"].values


# convert date string into datetime object
reviews["date"] = pd.to_datetime(reviews["date"])

for k, business_id in enumerate(business_ids):
    if k % 100 == 0:
        print(f"[{k}] - Conversion for business_id: {business_id}")

    # get temporary dataframe of all reviews with given business_id and assign column 'Number' (Rating 0, ..., M_i)
    df_temp = (
        reviews[reviews["business_id"] == business_id]
        .reset_index(drop=True)
        .assign(Number=lambda x: x.index)
    )

    # calculate days since first review
    df_temp["Days"] = (df_temp["date"] - df_temp["date"].iloc[0]).dt.days
    days.extend(df_temp["Days"].tolist())
    sentiment.extend(df_temp["sentimenttext"].tolist())
    ratings.extend(df_temp["stars"].tolist())
    time.append(len(df_temp))
    age.append(df_temp["Days"].iloc[-1])


# validation checks
assert sum(time) == len(sentiment)
assert len(days) == len(sentiment)
assert len(ratings) == len(sentiment)
print("Done ... validation checks passed!")

[0] - Conversion for business_id: QkG3KUXwqZBW18A9k1xqCA
[100] - Conversion for business_id: 7kmHtcImdFJrPejNNP4TMg
[200] - Conversion for business_id: ZE1n6H-4qgq_7z67qa4yUA
[300] - Conversion for business_id: NxZIySJr3DjROJBkl_KaEg
[400] - Conversion for business_id: bjrPt4DN1r4HpiR0Y8ofvg
[500] - Conversion for business_id: HpRj2Lv27EUQql0POE5sQw
[600] - Conversion for business_id: auDjameQ8PKA2cIwyI5uQA
[700] - Conversion for business_id: rjlAUHT8B6KhKAmkZqS1xw
[800] - Conversion for business_id: jMPPJmQBBa3iRuWbYbj1Gg
[900] - Conversion for business_id: KFrJTt-NTXUrsdr7BGx5dg
Done ... validation checks passed!

In [23]:
assert (
    not "Age" in business_covariates
), "The key Age is already added to dataframe! Make sure, that you only run this cell once!"

# add restaurant age in days to dataframe
business_covariates["Age"] = age


# change checkin count to checkin rates (number of checkins every month, assuming a month contains 28 days)
business_covariates["Checkin"] = (
    business_covariates["Checkin"] / business_covariates["Age"] * 28
)

# add log of age to dataframe for later analysis
business_covariates["logAge"] = np.log(business_covariates["Age"])

# only get relevant covariates for analysis
relevant_covariates = business_covariates[
    [
        "Age",
        "Checkin",
        "density",
        "chain",
        "category",
        "Restaurant.Size",
        "Number.of.Seats",
        "ZRI",
    ]
]

relevant_covariates

,Age,Checkin,density,chain,category,Restaurant.Size,Number.of.Seats,ZRI
0,2057,2.327662,11,1,American,700.0,350.0,1248.0
1,744,2.220430,17,0,American,200.0,30.0,1557.0
2,187,12.577540,1,0,Asian,280.0,70.0,1291.0
3,417,25.179856,4,0,Asian,90.0,35.0,1557.0
4,1872,2.108974,4,0,American,250.0,120.0,1495.0
...,...,...,...,...,...,...,...,...
916,1798,6.711902,4,1,Salad,220.0,70.0,1710.0
917,328,8.280488,7,0,Asian,190.0,24.0,1710.0
918,2423,1.086257,2,0,Pizza,120.0,84.0,1638.0
919,2811,0.488083,4,0,Asian,182.0,52.0,1287.0
920,565,5.847788,2,0,Mexican,NaN,NaN,1515.0

In [24]:
# from sklearn.preprocessing import OneHotEncoder
# from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

assert (
    len(relevant_covariates.columns) == 8
), "One Hot Coding and Scaling  already performed on dataframe!"

# extract categorical and numerical columns
cat_cols = relevant_covariates.select_dtypes(include=["object", "category"]).columns
num_cols = relevant_covariates.select_dtypes(include=["number"]).columns


# transform categorical columns to one hot encoded columns inidicating True/1 if category matches, False/0 else (numerical values stay the same)
# preprocessor = ColumnTransformer(
#     transformers=[
#         ("cat", OneHotEncoder(drop="first", sparse_output=False), cat_cols),
#         ("num", "passthrough", num_cols),
#     ]
# )

# cov_mat = preprocessor.fit_transform(relevant_covariates)


# same effect with already named columns (category_<categoryName>)
relevant_covariates = pd.get_dummies(relevant_covariates, drop_first=False)

relevant_covariates.head(1)

,Age,Checkin,density,chain,Restaurant.Size,Number.of.Seats,ZRI,category_American,category_Asian,category_Cafes,category_Fast Food,category_Mexican,category_Other,category_Pizza,category_Salad,category_Speciality Food
0,2057,2.327662,11,1,700.0,350.0,1248.0,True,False,False,False,False,False,False,False,False

In [25]:
# replace missing values with median and center values
imputer = SimpleImputer(strategy="median")
scaler = StandardScaler(with_std=False)  # only centering, no scaling!

# create indices for training evaluation and calibration

indices = np.random.permutation(len(business_covariates))

train_indices = indices[:500]
calibration_indices = indices[500:700]
eval_indices = indices[:700]

N_train = len(train_indices)  # number of training samples

X_train = relevant_covariates.iloc[:N_train].copy()

imputer.fit(X_train)
scaler.fit(X_train)

cov_mat_preprocessed = scaler.transform(imputer.transform(relevant_covariates.values))
X_train_preprocessed = cov_mat_preprocessed[:N_train]

# QR-decomposition
Q, R = np.linalg.qr(X_train_preprocessed)

Q_scaled = Q * np.sqrt(N_train - 1)
R_scaled = R / np.sqrt(N_train - 1)

X_test = cov_mat_preprocessed[N_train:]

/Users/omidsedighi-mornani/Desktop/STUDIUM WIRTSCHAFTSINFORMATIK/Semester 5/Seminar Gust/SourceCode/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(
/Users/omidsedighi-mornani/Desktop/STUDIUM WIRTSCHAFTSINFORMATIK/Semester 5/Seminar Gust/SourceCode/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [26]:
# store all data in pickle file for later usage
import pickle

data = {
    "S": None,  # NA in R = None in Python
    "N_total": len(time),
    "N_train": N_train,
    "N_obs": np.sum(time),
    "n_covs": cov_mat_preprocessed.shape[1],
    "time": time,
    "closed": 1 - business_covariates["is_open"].values,
    "days": days,
    "ratings": ratings,
    "sentiment": sentiment,
    "Q": Q_scaled,
    "R": R_scaled,
    "X_test": X_test,
}

data_to_save = {
    "data": data,
    "imputer": imputer,
    "scaler": scaler,
    "train_indices": train_indices,
    "calibration_indices": calibration_indices,
    "eval_indices": eval_indices,
    "business_covariates": business_covariates,
    "cov_mat": cov_mat_preprocessed,
}

# write data
with open(data_folder / "processed/processed_data.pkl", "wb") as file:
    pickle.dump(data_to_save, file)